<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class MjestosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
  public function run() {
    DB::table('mjestos')->delete();
    DB::table('mjestos')->insert(
        [
          array(// row #0
            'pbr' => 10000,
            'naziv' => 'Zagreb',
            'zupanija_id' => 22,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => '2017-06-07 17:37:17',
          ),
          array(// row #1
            'pbr' => 10010,
            'naziv' => 'Zagreb-Sloboština',
            'zupanija_id' => 22,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #2
            'pbr' => 10020,
            'naziv' => 'Zagreb-Novi Zagreb',
            'zupanija_id' => 22,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #3
            'pbr' => 10040,
            'naziv' => 'Zagreb-Dubrava',
            'zupanija_id' => 22,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #4
            'pbr' => 10090,
            'naziv' => 'Zagreb-Susedgrad',
            'zupanija_id' => 22,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #5
            'pbr' => 10250,
            'naziv' => 'Lučko',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #6
            'pbr' => 10255,
            'naziv' => 'Gornji Stupnik',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #7
            'pbr' => 10290,
            'naziv' => 'Zaprešić',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #8
            'pbr' => 10295,
            'naziv' => 'Kupljenovo',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #9
            'pbr' => 10310,
            'naziv' => 'Ivanić-Grad',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #10
            'pbr' => 10315,
            'naziv' => 'Novoselec',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #11
            'pbr' => 10340,
            'naziv' => 'Vrbovec',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #12
            'pbr' => 10345,
            'naziv' => 'Gradec',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #13
            'pbr' => 10360,
            'naziv' => 'Sesvete',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #14
            'pbr' => 10370,
            'naziv' => 'Dugo Selo',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #15
            'pbr' => 10380,
            'naziv' => 'Sveti Ivan Zelina',
            'zupanija_id' => 22,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #16
            'pbr' => 10410,
            'naziv' => 'Velika Gorica',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #17
            'pbr' => 10415,
            'naziv' => 'Novo Čiče',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #18
            'pbr' => 10430,
            'naziv' => 'Samobor',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #19
            'pbr' => 10435,
            'naziv' => 'Sveti Martin pod Okićem',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #20
            'pbr' => 10450,
            'naziv' => 'Jastrebarsko',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #21
            'pbr' => 10455,
            'naziv' => 'Kostanjevac',
            'zupanija_id' => 2,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => '2017-06-09 17:06:41',
          ),
          array(// row #22
            'pbr' => 20000,
            'naziv' => 'Dubrovnik',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #23
            'pbr' => 20205,
            'naziv' => 'Topolo',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #24
            'pbr' => 20210,
            'naziv' => 'Cavtat',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #25
            'pbr' => 20215,
            'naziv' => 'Gruda',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #26
            'pbr' => 20225,
            'naziv' => 'Babino Polje',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #27
            'pbr' => 20230,
            'naziv' => 'Ston',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #28
            'pbr' => 20235,
            'naziv' => 'Zaton Veliki',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #29
            'pbr' => 20240,
            'naziv' => 'Trpanj',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #30
            'pbr' => 20242,
            'naziv' => 'Oskorušno',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #31
            'pbr' => 20245,
            'naziv' => 'Trstenik',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #32
            'pbr' => 20250,
            'naziv' => 'Orebić',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #33
            'pbr' => 20260,
            'naziv' => 'Korčula',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #34
            'pbr' => 20270,
            'naziv' => 'Vela Luka',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #35
            'pbr' => 20275,
            'naziv' => 'Žrnovo',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #36
            'pbr' => 20290,
            'naziv' => 'Lastovo',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #37
            'pbr' => 20340,
            'naziv' => 'Ploče',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #38
            'pbr' => 20345,
            'naziv' => 'Staševica',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #39
            'pbr' => 20350,
            'naziv' => 'Metković',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #40
            'pbr' => 20355,
            'naziv' => 'Opuzen',
            'zupanija_id' => 20,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #41
            'pbr' => 21000,
            'naziv' => 'Split',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #42
            'pbr' => 21205,
            'naziv' => 'Donji Dolac',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #43
            'pbr' => 21210,
            'naziv' => 'Solin',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #44
            'pbr' => 21215,
            'naziv' => 'Kaštel Lukšić',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #45
            'pbr' => 21220,
            'naziv' => 'Trogir',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #46
            'pbr' => 21225,
            'naziv' => 'Drvenik Veliki',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #47
            'pbr' => 21230,
            'naziv' => 'Sinj',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #48
            'pbr' => 21232,
            'naziv' => 'Dicmo',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #49
            'pbr' => 21235,
            'naziv' => 'Otišić',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #50
            'pbr' => 21240,
            'naziv' => 'Trilj',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #51
            'pbr' => 21245,
            'naziv' => 'Tijarica',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #52
            'pbr' => 21250,
            'naziv' => 'Šestanovac',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #53
            'pbr' => 21255,
            'naziv' => 'Zadvarje',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #54
            'pbr' => 21260,
            'naziv' => 'Imotski',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #55
            'pbr' => 21265,
            'naziv' => 'Studenci',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #56
            'pbr' => 21270,
            'naziv' => 'Zagvozd',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #57
            'pbr' => 21275,
            'naziv' => 'Dragljane',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #58
            'pbr' => 21300,
            'naziv' => 'Makarska',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #59
            'pbr' => 21310,
            'naziv' => 'Omiš',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #60
            'pbr' => 21315,
            'naziv' => 'Dugi Rat',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #61
            'pbr' => 21320,
            'naziv' => 'Baška Voda',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #62
            'pbr' => 21325,
            'naziv' => 'Tučepi',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #63
            'pbr' => 21330,
            'naziv' => 'Gradac',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #64
            'pbr' => 21335,
            'naziv' => 'Podaca',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #65
            'pbr' => 21400,
            'naziv' => 'Supetar',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #66
            'pbr' => 21405,
            'naziv' => 'Milna',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #67
            'pbr' => 21410,
            'naziv' => 'Postira',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #68
            'pbr' => 21420,
            'naziv' => 'Bol',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #69
            'pbr' => 21425,
            'naziv' => 'Selca',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #70
            'pbr' => 21430,
            'naziv' => 'Grohote',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #71
            'pbr' => 21450,
            'naziv' => 'Hvar',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #72
            'pbr' => 21460,
            'naziv' => 'Stari Grad',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #73
            'pbr' => 21465,
            'naziv' => 'Jelsa',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #74
            'pbr' => 21480,
            'naziv' => 'Vis',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #75
            'pbr' => 21485,
            'naziv' => 'Komiža',
            'zupanija_id' => 18,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #76
            'pbr' => 22000,
            'naziv' => 'Šibenik',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #77
            'pbr' => 22010,
            'naziv' => 'Šibenik-Brodarica',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #78
            'pbr' => 22020,
            'naziv' => 'Šibenik-Ražine',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #79
            'pbr' => 22030,
            'naziv' => 'Šibenik-Zablaće',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #80
            'pbr' => 22205,
            'naziv' => 'Perković',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #81
            'pbr' => 22215,
            'naziv' => 'Zaton',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #82
            'pbr' => 22235,
            'naziv' => 'Kaprije',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #83
            'pbr' => 22240,
            'naziv' => 'Tisno',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #84
            'pbr' => 22300,
            'naziv' => 'Knin',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #85
            'pbr' => 22305,
            'naziv' => 'Kistanje',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #86
            'pbr' => 22310,
            'naziv' => 'Kijevo',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #87
            'pbr' => 22320,
            'naziv' => 'Drniš',
            'zupanija_id' => 16,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #88
            'pbr' => 23000,
            'naziv' => 'Zadar',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #89
            'pbr' => 23205,
            'naziv' => 'Bibinje',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #90
            'pbr' => 23210,
            'naziv' => 'Biograd na moru',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #91
            'pbr' => 23235,
            'naziv' => 'Vrsi',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #92
            'pbr' => 23245,
            'naziv' => 'Tribanj',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #93
            'pbr' => 23250,
            'naziv' => 'Pag',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #94
            'pbr' => 23275,
            'naziv' => 'Ugljan',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #95
            'pbr' => 23285,
            'naziv' => 'Brbinj',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #96
            'pbr' => 23295,
            'naziv' => 'Silba',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #97
            'pbr' => 23420,
            'naziv' => 'Benkovac',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #98
            'pbr' => 23440,
            'naziv' => 'Gračac',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #99
            'pbr' => 23445,
            'naziv' => 'Srb',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #100
            'pbr' => 23450,
            'naziv' => 'Obrovac',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #101
            'pbr' => 31000,
            'naziv' => 'Osijek',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #102
            'pbr' => 31205,
            'naziv' => 'Aljmaš',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #103
            'pbr' => 31215,
            'naziv' => 'Ernestinovo',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #104
            'pbr' => 31220,
            'naziv' => 'Višnjevac',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #105
            'pbr' => 31225,
            'naziv' => 'Breznica Našička',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #106
            'pbr' => 31300,
            'naziv' => 'Beli Manastir',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #107
            'pbr' => 31301,
            'naziv' => 'Branjin Vrh',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #108
            'pbr' => 31305,
            'naziv' => 'Draž',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #109
            'pbr' => 31315,
            'naziv' => 'Karanac',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #110
            'pbr' => 31325,
            'naziv' => 'Čeminac',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #111
            'pbr' => 31400,
            'naziv' => 'Đakovo',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #112
            'pbr' => 31410,
            'naziv' => 'Strizivojna',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #113
            'pbr' => 31415,
            'naziv' => 'Selci Đakovački',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #114
            'pbr' => 31500,
            'naziv' => 'Našice',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #115
            'pbr' => 31530,
            'naziv' => 'Podravska Moslavina',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #116
            'pbr' => 31531,
            'naziv' => 'Viljevo',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #117
            'pbr' => 31540,
            'naziv' => 'Donji Miholjac',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #118
            'pbr' => 31550,
            'naziv' => 'Valpovo',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #119
            'pbr' => 31555,
            'naziv' => 'Marijanci',
            'zupanija_id' => 15,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #120
            'pbr' => 32000,
            'naziv' => 'Vukovar',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #121
            'pbr' => 32100,
            'naziv' => 'Vinkovci',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #122
            'pbr' => 32225,
            'naziv' => 'Bobota',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #123
            'pbr' => 32235,
            'naziv' => 'Bapska',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #124
            'pbr' => 32240,
            'naziv' => 'Mirkovci',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #125
            'pbr' => 32245,
            'naziv' => 'Nijemci',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #126
            'pbr' => 32255,
            'naziv' => 'Soljani',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #127
            'pbr' => 32260,
            'naziv' => 'Gunja',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #128
            'pbr' => 32270,
            'naziv' => 'Županja',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #129
            'pbr' => 32275,
            'naziv' => 'Bošnjaci',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #130
            'pbr' => 32280,
            'naziv' => 'Jarmina',
            'zupanija_id' => 17,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #131
            'pbr' => 33000,
            'naziv' => 'Virovitica',
            'zupanija_id' => 11,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #132
            'pbr' => 33333,
            'naziv' => 'trice',
            'zupanija_id' => 14,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #133
            'pbr' => 33405,
            'naziv' => 'Pitomača',
            'zupanija_id' => 11,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #134
            'pbr' => 33410,
            'naziv' => 'Suhopolje',
            'zupanija_id' => 11,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #135
            'pbr' => 33515,
            'naziv' => 'Orahovica',
            'zupanija_id' => 11,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #136
            'pbr' => 33520,
            'naziv' => 'Slatina',
            'zupanija_id' => 11,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #137
            'pbr' => 33525,
            'naziv' => 'Sopje',
            'zupanija_id' => 11,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #138
            'pbr' => 34000,
            'naziv' => 'Požega',
            'zupanija_id' => 12,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #139
            'pbr' => 34310,
            'naziv' => 'Pleternica',
            'zupanija_id' => 12,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #140
            'pbr' => 34315,
            'naziv' => 'Ratkovica',
            'zupanija_id' => 12,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #141
            'pbr' => 34320,
            'naziv' => 'Orljavac',
            'zupanija_id' => 12,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #142
            'pbr' => 34330,
            'naziv' => 'Velika',
            'zupanija_id' => 12,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #143
            'pbr' => 34335,
            'naziv' => 'Vetovo',
            'zupanija_id' => 12,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #144
            'pbr' => 34340,
            'naziv' => 'Kutjevo',
            'zupanija_id' => 12,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #145
            'pbr' => 34350,
            'naziv' => 'Čaglin',
            'zupanija_id' => 12,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #146
            'pbr' => 34550,
            'naziv' => 'Pakrac',
            'zupanija_id' => 12,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #147
            'pbr' => 35000,
            'naziv' => 'Slavonski Brod',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #148
            'pbr' => 35210,
            'naziv' => 'Vrpolje',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #149
            'pbr' => 35215,
            'naziv' => 'Svilaj',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #150
            'pbr' => 35220,
            'naziv' => 'Slavonski Šamac',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #151
            'pbr' => 35250,
            'naziv' => 'Oriovac',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #152
            'pbr' => 35255,
            'naziv' => 'Slavonski Kobaš',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #153
            'pbr' => 35400,
            'naziv' => 'Nova Gradiška',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #154
            'pbr' => 35420,
            'naziv' => 'Staro Petrovo Selo',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #155
            'pbr' => 35425,
            'naziv' => 'Davor',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #156
            'pbr' => 35430,
            'naziv' => 'Okučani',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #157
            'pbr' => 35435,
            'naziv' => 'Stara Gradiška',
            'zupanija_id' => 13,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #158
            'pbr' => 40000,
            'naziv' => 'Čakovec',
            'zupanija_id' => 21,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #159
            'pbr' => 40305,
            'naziv' => 'Nedelišče',
            'zupanija_id' => 21,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #160
            'pbr' => 40315,
            'naziv' => 'Mursko Središče',
            'zupanija_id' => 21,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #161
            'pbr' => 40320,
            'naziv' => 'Donji Kraljevec',
            'zupanija_id' => 21,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #162
            'pbr' => 40325,
            'naziv' => 'Draškovec',
            'zupanija_id' => 21,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #163
            'pbr' => 42000,
            'naziv' => 'Varaždin',
            'zupanija_id' => 6,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #164
            'pbr' => 42205,
            'naziv' => 'Vidovec',
            'zupanija_id' => 6,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #165
            'pbr' => 42220,
            'naziv' => 'Novi Marof',
            'zupanija_id' => 6,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #166
            'pbr' => 42225,
            'naziv' => 'Breznički Hum',
            'zupanija_id' => 6,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #167
            'pbr' => 42230,
            'naziv' => 'Ludbreg',
            'zupanija_id' => 6,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #168
            'pbr' => 42240,
            'naziv' => 'Ivanec',
            'zupanija_id' => 6,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #169
            'pbr' => 42245,
            'naziv' => 'Donja Voća',
            'zupanija_id' => 6,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #170
            'pbr' => 42250,
            'naziv' => 'Lepoglava',
            'zupanija_id' => 6,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #171
            'pbr' => 42255,
            'naziv' => 'Donja Višnjica',
            'zupanija_id' => 6,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #172
            'pbr' => 43000,
            'naziv' => 'Bjelovar',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #173
            'pbr' => 43240,
            'naziv' => 'Čazma',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #174
            'pbr' => 43245,
            'naziv' => 'Gornji Draganec',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #175
            'pbr' => 43270,
            'naziv' => 'Veliki Grđevac',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #176
            'pbr' => 43271,
            'naziv' => 'Velika Pisanica',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #177
            'pbr' => 43280,
            'naziv' => 'Garešnica',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #178
            'pbr' => 43285,
            'naziv' => 'Velika Trnovitica',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #179
            'pbr' => 43290,
            'naziv' => 'Grubišno Polje',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #180
            'pbr' => 43500,
            'naziv' => 'Daruvar',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #181
            'pbr' => 43505,
            'naziv' => 'Končanica',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #182
            'pbr' => 43531,
            'naziv' => 'Veliki Bastaji',
            'zupanija_id' => 8,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #183
            'pbr' => 44000,
            'naziv' => 'Sisak',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #184
            'pbr' => 44010,
            'naziv' => 'Sisak-Caprag',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #185
            'pbr' => 44205,
            'naziv' => 'Donja Bačuga',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #186
            'pbr' => 44210,
            'naziv' => 'Sunja',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #187
            'pbr' => 44250,
            'naziv' => 'Petrinja',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #188
            'pbr' => 44271,
            'naziv' => 'Letovanić',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #189
            'pbr' => 44320,
            'naziv' => 'Kutina',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #190
            'pbr' => 44325,
            'naziv' => 'Krapje',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #191
            'pbr' => 44330,
            'naziv' => 'Novska',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #192
            'pbr' => 44400,
            'naziv' => 'Glina',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #193
            'pbr' => 44405,
            'naziv' => 'Mali Gradac',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #194
            'pbr' => 44410,
            'naziv' => 'Gvozd',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #195
            'pbr' => 44415,
            'naziv' => 'Topusko',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #196
            'pbr' => 44425,
            'naziv' => 'Gornja Bučica',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #197
            'pbr' => 44430,
            'naziv' => 'Hrvatska Kostajnica',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #198
            'pbr' => 44435,
            'naziv' => 'Divuša',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #199
            'pbr' => 44440,
            'naziv' => 'Dvor',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #200
            'pbr' => 44450,
            'naziv' => 'Hrvatska Dubica',
            'zupanija_id' => 4,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #201
            'pbr' => 47000,
            'naziv' => 'Karlovac',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #202
            'pbr' => 47201,
            'naziv' => 'Draganići',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #203
            'pbr' => 47205,
            'naziv' => 'Vukmanić',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #204
            'pbr' => 47220,
            'naziv' => 'Vojnić',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #205
            'pbr' => 47240,
            'naziv' => 'Slunj',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #206
            'pbr' => 47245,
            'naziv' => 'Rakovica',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #207
            'pbr' => 47250,
            'naziv' => 'Duga Resa',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #208
            'pbr' => 47251,
            'naziv' => 'Bosiljevo',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #209
            'pbr' => 47280,
            'naziv' => 'Ozalj',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #210
            'pbr' => 47285,
            'naziv' => 'Radatovići',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #211
            'pbr' => 47300,
            'naziv' => 'Ogulin',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #212
            'pbr' => 47302,
            'naziv' => 'Oštarije',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #213
            'pbr' => 47305,
            'naziv' => 'Lička Jesenica',
            'zupanija_id' => 5,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #214
            'pbr' => 48000,
            'naziv' => 'Koprivnica',
            'zupanija_id' => 7,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #215
            'pbr' => 48260,
            'naziv' => 'Križevci',
            'zupanija_id' => 7,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #216
            'pbr' => 48265,
            'naziv' => 'Raven',
            'zupanija_id' => 7,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #217
            'pbr' => 48305,
            'naziv' => 'Reka',
            'zupanija_id' => 7,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #218
            'pbr' => 48325,
            'naziv' => 'Novigrad Podravski',
            'zupanija_id' => 7,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #219
            'pbr' => 48350,
            'naziv' => 'Đurđevac',
            'zupanija_id' => 7,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #220
            'pbr' => 48355,
            'naziv' => 'Novo Virje',
            'zupanija_id' => 7,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #221
            'pbr' => 49000,
            'naziv' => 'Krapina',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #222
            'pbr' => 49210,
            'naziv' => 'Zabok',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #223
            'pbr' => 49215,
            'naziv' => 'Tuhelj',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #224
            'pbr' => 49225,
            'naziv' => 'Đurmanec',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #225
            'pbr' => 49240,
            'naziv' => 'Donja Stubica',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #226
            'pbr' => 49245,
            'naziv' => 'Gornja Stubica',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #227
            'pbr' => 49250,
            'naziv' => 'Zlatar',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #228
            'pbr' => 49255,
            'naziv' => 'Novi Golubovec',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #229
            'pbr' => 49290,
            'naziv' => 'Klanjec',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #230
            'pbr' => 49295,
            'naziv' => 'Kumrovec',
            'zupanija_id' => 3,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #231
            'pbr' => 51000,
            'naziv' => 'Rijeka',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #232
            'pbr' => 51211,
            'naziv' => 'Matulji',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #233
            'pbr' => 51215,
            'naziv' => 'Kastav',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #234
            'pbr' => 51225,
            'naziv' => 'Praputnjak',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #235
            'pbr' => 51250,
            'naziv' => 'Novi Vinodolski',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #236
            'pbr' => 51251,
            'naziv' => 'Ledenice',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #237
            'pbr' => 51260,
            'naziv' => 'Crikvenica',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #238
            'pbr' => 51265,
            'naziv' => 'Dramalj',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #239
            'pbr' => 51280,
            'naziv' => 'Rab',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #240
            'pbr' => 51300,
            'naziv' => 'Delnice',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #241
            'pbr' => 51305,
            'naziv' => 'Tršće',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #242
            'pbr' => 51315,
            'naziv' => 'Mrkopalj',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #243
            'pbr' => 51325,
            'naziv' => 'Moravice',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #244
            'pbr' => 51410,
            'naziv' => 'Opatija',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #245
            'pbr' => 51415,
            'naziv' => 'Lovran',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #246
            'pbr' => 51500,
            'naziv' => 'Krk',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #247
            'pbr' => 51515,
            'naziv' => 'Šilo',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #248
            'pbr' => 51550,
            'naziv' => 'Mali Lošinj',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #249
            'pbr' => 51555,
            'naziv' => 'Belej',
            'zupanija_id' => 9,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #250
            'pbr' => 52000,
            'naziv' => 'Pazin',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #251
            'pbr' => 52100,
            'naziv' => 'Pula',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #252
            'pbr' => 52210,
            'naziv' => 'Rovinj (Rovigno)',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #253
            'pbr' => 52215,
            'naziv' => 'Vodnjan (Dignano)',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #254
            'pbr' => 52220,
            'naziv' => 'Labin',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #255
            'pbr' => 52420,
            'naziv' => 'Buzet',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #256
            'pbr' => 52425,
            'naziv' => 'Roč',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #257
            'pbr' => 52440,
            'naziv' => 'Poreč',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #258
            'pbr' => 52445,
            'naziv' => 'Baderna',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #259
            'pbr' => 52450,
            'naziv' => 'Vrsar',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #260
            'pbr' => 52460,
            'naziv' => 'Buje (Buie)',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #261
            'pbr' => 52465,
            'naziv' => 'Tar',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #262
            'pbr' => 52470,
            'naziv' => 'Umag (Umago)',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #263
            'pbr' => 52475,
            'naziv' => 'Savudrija (Salvore)',
            'zupanija_id' => 19,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #264
            'pbr' => 53000,
            'naziv' => 'Gospić',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #265
            'pbr' => 53205,
            'naziv' => 'Medak',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #266
            'pbr' => 53220,
            'naziv' => 'Otočac',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #267
            'pbr' => 53225,
            'naziv' => 'Švica',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #268
            'pbr' => 53230,
            'naziv' => 'Korenica',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #269
            'pbr' => 53235,
            'naziv' => 'Bunić',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #270
            'pbr' => 53250,
            'naziv' => 'Donji Lapac',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #271
            'pbr' => 53260,
            'naziv' => 'Brinje',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #272
            'pbr' => 53270,
            'naziv' => 'Senj',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          ),
          array(// row #273
            'pbr' => 53285,
            'naziv' => 'Lukovo',
            'zupanija_id' => 10,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => NULL,
          )
        ]
    );
  }

}

